import fs from "fs";
import path from "path";
import { findUpSync } from "find-up";
import toValidIdentifier from "to-valid-identifier";

const projectRoot = findUpSync("package.json")?.replace("package.json", "");

if (!projectRoot) {
  throw new Error("Could not find project root");
}

const soundAssetsDir = path.join(projectRoot, "assets", "sounds");
const files = fs
  .readdirSync(soundAssetsDir)
  .filter((file) => file.endsWith(".mp3"));

let imports = "";
for (const file of files) {
  const variableName = toValidIdentifier(file.replace(".mp3", ""));
  imports += `const ${variableName} = require('../../assets/sounds/${file}');\n`;
}

let exports = "const Clips = {\n";
for (const file of files) {
  const variableName = toValidIdentifier(file.replace(".mp3", ""));
  exports += `  ${variableName},\n`;
}
exports = exports.slice(0, -1) + "\n};\nexport default Clips;\n";

fs.writeFileSync(
  path.join(projectRoot, "constants", "generated", "Clips.ts"),
  `// Generated by scripts/update-audio-clips.ts\n\n${imports}\n${exports}`,
);
