name: Hello World

on:
  push:
    branches: ['*']

jobs:
  Part 1:
    steps:
      - run: echo "Hello, World (pt 1)"
  Part 2:
      needs: [Part 1]
      steps:
      - run: echo "Hello, World (pt 2)"
  Part 3:
    needs: [Part 1, Part 2]
    steps:
      - run: echo "Hello, World (pt 2)"